volumes:
  cosypolyamory:

services:

  web:
    build: .
    image: cosypolyamory-web
    restart: unless-stopped
    expose:
      - "3031"
    volumes:
      - cosypolyamory:/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-cosypolyamory.org}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-cosypolyamory.org}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-mayhem@gmail.com}
      - DATABASE_PATH=/data/cosypolyamory.db
      - UWSGI_PROCESSES=${UWSGI_PROCESSES:-8}
    command: ["/code/cosypolyamory.org/docker_startup.sh"]

  reminders:
    build: .
    image: cosypolyamory-reminders
    restart: unless-stopped
    volumes:
      - cosypolyamory:/data
    environment:
      - DATABASE_PATH=/data/cosypolyamory.db

    command: ["/code/cosypolyamory.org/send_event_reminders.py"]

networks:
  default:
    name: nginx-proxy
    external: true
